<?php

namespace AppBundle\Repository;

/**
 * DishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishRepository extends \Doctrine\ORM\EntityRepository
{
}
