<?php

namespace AppBundle\Repository;

/**
 * MusicAppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicAppRepository extends \Doctrine\ORM\EntityRepository
{
}
